# Generated by Django 2.2 on 2019-06-12 21:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 12, 21, 54, 26, 473128))),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('grade_type', models.CharField(choices=[('academic_grade', 'academic grade'), ('score_grade', 'score grade'), ('percent_grade', 'percent grade')], default='academic_grade', max_length=64)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='requesting',
            field=models.ManyToManyField(related_name='requesting', to='system.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='system.Student'),
        ),
        migrations.CreateModel(
            name='ScoreGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Student')),
            ],
            options={
                'unique_together': {('owner', 'event')},
            },
        ),
        migrations.CreateModel(
            name='PercentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Student')),
            ],
            options={
                'unique_together': {('owner', 'event')},
            },
        ),
        migrations.CreateModel(
            name='AcademicGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Student')),
            ],
            options={
                'unique_together': {('owner', 'event')},
            },
        ),
    ]
