# Generated by Django 2.2 on 2019-04-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
