# Generated by Django 2.2 on 2019-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190503_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('2.0', 'chlip'), ('3.0', 'ok'), ('4.0', 'dobre'), ('5.0', 'bardzodobre')], max_length=3),
        ),
    ]
