from .home import *
from .manage_groups import *
from .course_views import *
from .event_views import *
from .overview import *
from .profile import *
from .manage_students import *
from .manage_grades import *
from .search import *
